# Copyright 2020 Amazon.com Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

nameOverride: "eks-distro-pod-identity-webhook"
fullnameOverride: "eks-distro-pod-identity-webhook"
webhookConfigName: "0500-eks-distro-pod-identity-webhook"
installJobName: "eks-distro-pod-identity-webhook-cert-approver"
uninstallJobName: "eks-distro-pod-identity-webhook-cleaner"

# Make sure to pass in the image for the webhook here or as a parameter to the helm installation
image: placeholder-webhook:fake

# Used for sleep containers as well as to run our job script
baseImage: public.ecr.aws/amazonlinux/amazonlinux:2 

# Adding the value for 'sleep' in seconds as a sleep to the deployment to allow for the webhook to be able to talk to kube-apiserver
# as fargate pods take longer to bootstrap.
sleep: 30
fargate: false

# Parameters to webhook are defined here: https://github.com/aws/amazon-eks-pod-identity-webhook#usage
webhook:
  tokenExpiration: 3600
  stsRegionalEndpoint: true
  port: 443
  metricsPort: 9999

service:
  port: 443

replicaCount: 1
